services:
  - type: web
    plan: free
    runtime: image
    name: n8n-service
    image:
      url: docker.io/n8nio/n8n:latest
    envVars:
      - key: N8N_ENCRYPTION_KEY
        value: ${N8N_ENCRYPTION_KEY}

      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_DATABASE
        value: ${DB_POSTGRESDB_DATABASE}
      - key: DB_POSTGRESDB_HOST
        value: ${DB_POSTGRESDB_HOST}
      - key: DB_POSTGRESDB_PORT
        value: ${DB_POSTGRESDB_PORT}
      - key: DB_POSTGRESDB_USER
        value: ${DB_POSTGRESDB_USER}
      - key: DB_POSTGRESDB_PASSWORD
        value: ${DB_POSTGRESDB_PASSWORD}

      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_PORT
        value: "3000"
      - key: WEBHOOK_URL
        value: ${N8N_WEBHOOK_URL}
